# Generated by Django 5.1.3 on 2024-12-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
